name: ğŸ¤– CI
on:
  pull_request:
    branches:
      - main

jobs:
  client:
    name: 'Client Tests'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout ğŸ›'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node ğŸ—
        uses: actions/setup-node@v2
        with:
          node-version: 16.18

      - name: 'Install yarn dependencies ğŸ§¶'
        run: |
          npm install -g yarn
          yarn workspace @tictactoe/client install  --immutable

      - name: 'Jest ğŸƒ'
        run: |
          yarn workspace @tictactoe/client test --watchAll=false

  server:
    name: 'Server Tests'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout ğŸ›'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node ğŸ—
        uses: actions/setup-node@v2
        with:
          node-version: 16.18

      - name: 'Install yarn dependencies ğŸ§¶'
        run: |
          npm install -g yarn
          yarn workspace @tictactoe/client install  --immutable

      - name: 'Jest ğŸƒ'
        run: |
          yarn workspace @tictactoe/server test --watchAll=false
